### ISSUE TITLE
[버그] 게임재시작 버튼 눌렀을 시 간헐적으로 OutOfMemoryExcption : Out of memory 발생 

### ISSUE THREAD

**Issue by mocha-rm** [pktony/Choksu_Run#13]

**Comment by pktony** [comment]
어디서 에러가 나는지 파악 후 조치

**Comment by mocha-rm** [comment]
게임 재시작, 홈으로 이동 눌렀을 때 SceneLoadManager에서 발생
코루틴 while문 밖에 yield문 하나 더 추가로 해결 된 듯? 몇번 테스트 했는데 문제 없었음 

![OutOfMemoryException - Out of memory](https://github.com/pktony/Choksu_Run/assets/109475391/686b2ad9-0189-4e67-8c25-310677236f80)
![OOM](https://github.com/pktony/Choksu_Run/assets/109475391/68344b0e-e135-4a3d-8bd2-f0fdababab4e)
![OOM2](https://github.com/pktony/Choksu_Run/assets/109475391/8e8529bf-f5d7-40da-844f-c07b6141a01c)
